name: Build and publish image to Docker Hub & AWS CI/CD
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-flask-third-api:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-flask-third-api:latest

      - name: Push Docker image to Amazon ECR
        run: |
          aws_account_id=${{ secrets.AWS_ACCOUNT_ID }}
          aws_region=${{ secrets.AWS_REGION }}
          ecr_repository_name=my-flask-third-api
          docker tag ${{ secrets.DOCKER_USERNAME }}/my-flask-third-api:latest $aws_account_id.dkr.ecr.$aws_region.amazonaws.com/$ecr_repository_name:latest
          docker push $aws_account_id.dkr.ecr.$aws_region.amazonaws.com/$ecr_repository_name:latest
